version: "3.8"
services:
  backend:
    build: 
      context: ./backend
      target: prod
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: "file:./prisma/dev.db"
    volumes:
      - backend_data:/app/prisma
    restart: always
  frontend:
    build: 
      context: ./frontend
      target: prod
    ports:
      - "80:80"
    depends_on: 
      - backend
    restart: always
volumes:
  backend_data:
